version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: todo-backend-dev
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - MONGODB_HOST=mongo
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=example
    volumes:
      - ./:/usr/src/app                 # Mount local code
      - /usr/src/app/node_modules       # Keep container node_modules separate
    depends_on:
      - redis
      - mongo
    command: nodemon --legacy-watch index.js

  mongo:
    image: mongo:5
    container_name: todo-mongo-dev
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - todo-mongo-data:/data/db

  redis:
    image: redis:7
    container_name: todo-redis-dev
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  todo-mongo-data:
