version: "3.8"

services:
  frontend:
    image: node:18
    container_name: todo-frontend-dev
    working_dir: /usr/src/app
    ports:
      - "5173:5173"        # Vite default dev server port
    environment:
      - VITE_BACKEND_URL=http://host.docker.internal:3000
    volumes:
      - ./:/usr/src/app    # Mount local folder into container
      - /usr/src/app/node_modules  # Persist node_modules inside container
    command: sh -c "npm install && npm run dev"
