services:
  app:
    build:
      context: ./todo-frontend
      dockerfile: dev.Dockerfile
    container_name: todo-frontend-dev2
    volumes:
      - ./todo-frontend:/usr/src/app
    environment:
      - VITE_BACKEND_URL=http://server:3000
    ports:
      - "5173:5173"

  server:
    build:
      context: ./todo-backend
      dockerfile: dev.Dockerfile
    container_name: todo-backend-dev
    volumes:
      - ./todo-backend:/usr/src/app
    environment:
      - REDIS_HOST=todo-redis
      - MONGODB_HOST=todo-mongo
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=example
    ports:
      - "3000:3000"

  mongo:
    image: mongo:5
    container_name: todo-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - todo-mongo-data:/data/db

  redis:
    image: redis:7
    container_name: todo-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  todo-mongo-data:
